---
- name: provision hosts
  hosts: localhost
  gather_facts: False

  vars:
    - myname: zyre-gateway

  vars_files:
    - "aws_defaults.yml"

  tasks:
    - name: provisioning ec2 instance
      ec2:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        key_name: "wes"
        wait: True
        image: "{{ aws_base_ami }}"
        instance_type: "{{ aws_instance_type }}"
        instance_tags:
          Name: "{{ myname }}"
        vpc_subnet_id: "{{ aws_subnet_name }}"
        group_id: "{{ aws_security_group_name }}"
        private_ip: '{{ aws_private_ip }}'
        #termination_protection: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.private_ip }}"
        groupname: launched
        name: "{{ myname }}"
        ansible_host: "{{ item.private_ip }}"
        ansible_user: ubuntu
        ansible_private_key_file: "~/.ssh/id_rsa"
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for: host="{{ item.private_ip }}" port=22 delay=60 timeout=360 state=started
      with_items: "{{ ec2.instances }}"

    - name: associate elastic ip
      ec2_eip: device_id="{{ ec2.instances[0].id }}" ip="{{ aws_eip }}" region="{{ aws_region }}" profile="{{ aws_profile }}"

- name: bootstrap python
  hosts: launched
  gather_facts: False
  become: True

  vars_files:
    - "aws_defaults.yml"

  tasks:

    - name: configure python
      raw: sudo apt-get update && sudo apt-get install python-minimal aptitude -y
      register: result
      until: result.rc == 0
      retries: 20
      delay: 5

    - setup:
       filter: ansible_*

    # 1 GB
    - name: setup swap
      shell: |
        dd if=/dev/zero of=/swapfile bs=1024 count=1048576 \
        && mkswap /swapfile && chmod 0600 /swapfile && swapon /swapfile

    - name: Add swapfile to /etc/fstab
      lineinfile: dest=/etc/fstab line="/swapfile   none    swap    sw    0   0" state=present

- import_playbook: site.yml
