# https://thomas-leister.de/en/mailserver-debian-stretch/
# https://words.bombast.net/rspamd-with-postfix-dovecot-debian-stretch/#03

---
- name: "Configure"
  hosts: launched
  become: True

  # Fill these in first!
  vars_files:
    - "aws_defaults.yml"

  vars:
    pyzyre_version: '0.0.0a25'
    #pyzyre_version: 'master'
    #pyzyre_debug: True

    app_user: zyre
    app_group: zyre
    zyre_group: group1

    zyre_broker_node_name: 'zyre-broker'
    zyre_broker_gossip_bind: 'tcp://{{ aws_private_ip }}:49154'
    zyre_broker_endpoint: 'tcp://{{ aws_private_ip }}:49155'
    zyre_broker_advertise_endpoint: 'tcp://{{ aws_eip }}:49155'

    # to generate your keys- install pyzyre locally

    # $ mkdir ~/.curve && chmod 770 ~/.curve
    # $ zyre-certs

    # use keys from ~/.curve/test.key_secret here

    # or use these AT YOUR OWN RISK!!!

    #zyre_broker_publickey: '&%Uv$SlszDb4RWZw30VXtd^zH/JR6omz&-Ok&&5.'
    #zyre_broker_secretkey: '4)}j$^-{$JhngCSBUP1Po7CpbL8HYEtTlCcvbS4F'

  pre_tasks:
    - hostname:
        name: "zyre-broker"

  roles:
    - { role: zyre, tags: role-zyre }

  post_tasks:
