---

- name: install pyzmq
  pip: name="{{ item }}" extra_args='--no-binary :all:'
  with_items:
    - pyzmq==17.1.0

- name: install pyzyre
  environment:
    PYZYRE_BUILD_MASTER_CZMQ: 1
    PYZYRE_BUILD_MASTER_ZYRE: 1
  pip: name="{{ item }}"
  with_items:
     - "pyzyre=={{ pyzyre_version }}"
  notify: restart zyre
  when: pyzyre_debug is undefined or pyzyre_debug == False

- include_tasks: sdist.yml
  when: pyzyre_debug is defined and pyzyre_debug == True

- name: test
  command: zyre-broker -h
